### ISSUE TITLE
GRPC incompatibility

### ISSUE THREAD

**Issue by vitalinfo** [newrelic/newrelic-ruby-agent#1369] opened 2022-09-01 13:43 UTC
STR:
```
client = Google::Cloud::Translate::V3::TranslationService::Client.new do |config|
  config.credentials = JSON.parse(CREDENTIALS))
end
```

it raises an exception `ArgumentError (wrong number of arguments (given 3, expected 2)):`
because of 
```
.../gems/grpc-1.48.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:98:in `initialize'
.../gems/newrelic_rpm-8.10.0/lib/new_relic/agent/instrumentation/grpc/client/prepend.rb:18:in `initialize'
.../gems/grpc-1.48.0-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:158:in `initialize'
```

**Versions:** 
- `newrelic_rpm (8.10.0)` 
- `grpc-1.48.0` 
- `google-cloud-translate-v3 (0.3.0)`

**Comment by fallwith** [comment] 2022-09-01 16:40
Hi, @vitalinfo,

Thank you very much for bringing this issue to our attention and we're sorry to hear that you are experiencing an incompatibility with the new gRPC instrumentation.

The "wrong number of arguments" error that you are seeing seems very similar to #1337.

Essentially, we have committed a fix in our `dev` branch that will make it into a new gem version in the future. The gRPC instrumentation has been changed to no longer involve the method that is complaining about argument counts.

For now, you can either disable the gRPC instrumentation or point your `Gemfile` at our `dev` branch to pick up the fix. Instructions are at the bottom of the #1337 comments [here](https://github.com/newrelic/newrelic-ruby-agent/issues/1337#issuecomment-1224538977).

**Comment by fallwith** [comment] 2022-09-06 20:41
Closing as a duplicate of #1337. The fix is currently in the `dev` branch and will go out with the upcoming v8.11.0 release of the Ruby agent gem.

**Closed by fallwith** 2022-09-06 20:41 UTC
Labels: bug, community
