### ISSUE TITLE
Logs are being polluted by seemingly harmless JSON::ParserErrors (6.14.0)

### ISSUE THREAD

**Issue by fabubaker** [newrelic/newrelic-ruby-agent#512] opened 2020-12-02 07:21 UTC
## Description
Our logs are full of such lines:
```
** [NewRelic][2020-12-02 03:36:52 +0300 archiver-64fcff6d79-z4ftz (1)] ERROR : Error in read_response_headers
** [NewRelic][2020-12-02 03:36:52 +0300 archiver-64fcff6d79-z4ftz (1)] ERROR : JSON::ParserError: 795: unexpected token at '["650236#191670856","WebTransaction/Go/reviews/*/version",0,0.01088804,14,"a89580507ffb056a",false]'
** [NewRelic][2020-12-02 03:35:25 +0300 archiver-64fcff6d79-z4ftz (1)] ERROR : Error in read_response_headers
** [NewRelic][2020-12-02 03:35:25 +0300 archiver-64fcff6d79-z4ftz (1)] ERROR : JSON::ParserError: 795: unexpected token at 'u05e3o3$4>0957:0e#.wWb1R#;j(;g$bhovB</t)%ca8,9}wjuu-.7.4}04e25k3hl(vk(r?52=a257df44l4mf%)a`cqb_'
```

AFAIK, they don't really seem to be affect NR's reporting since we can still see metrics on our dashboards.

## Expected Behavior
These lines to not show up.

## Steps to Reproduce
Funnily enough we can't seem to reproduce this either locally or on staging. It happens exclusively on our production environment.

## Your Environment
Running on Kubernetes using the `ruby:2.3.8-jessie` docker image.
Docker version is `3.0.8`.
```
ruby (2.3.8)
rails (5.0.0)
newrelic_rpm (6.14.0)
```

**Comment by mwlang** [comment] 2020-12-02 18:58
@fabubaker Thank you for opening this issue with us.   This particular parsing error is attempting to parse cross-applicating-tracing (CAT) headers that important if you're using distributed-tracing to stitch together transaction events across multiple entities/services, all instrumented by New Relic agents.  A parsing error, at worst, results in a incomplete trace when trying to drill down into a trace that spans entities.  You will see separate transaction events in each instrumented entity with an opaque external call span to the other instead of one larger transaction event you can drill down in context.

The extracted examples are perplexing, though, and appear as though original character encoding is not preserved across the wire or something is rewriting header contents along the way.  This may be worth looking into to ensure it's not symptomatic of a misconfigured HTTP server or gateway somewhere in your infrastructure.  I am also checking into this further to ensure we are in fact correctly handling the contents of these headers you've posted examples of.

**Comment by fabubaker** [comment] 2020-12-05 11:41
Hi @mwlang, we tried disabling CAT by setting
```
distributed_tracing:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
   enabled: false           
```
in `newrelic.yml`, but we're still seeing the errors in our log. 

Shouldn't the errors go away if we do so?

**Comment by mwlang** [comment] 2020-12-08 20:40
@fabubaker I just took a look at the code and it looks like we have a latent bug here.  The Cross Application Tracing (CAT) feature is `on` when `distributed tracing` is disabled and off when enabled.  So, perhaps unintentionally, we're turning on and processing CAT headers if there's no an entry in the config to disable it, too.  Try the following:
```yaml
  distributed_tracing:
    enabled: false
  cross_application_tracer:
    enabled: false
```

**Comment by fabubaker** [comment] 2020-12-09 09:23
So that did the trick, but I'm a bit confused, what exactly is the difference between distributed tracing and cross application tracing?

I tried looking it up in the docs, but the verbiage seems similar

**Comment by mwlang** [comment] 2020-12-09 14:44
@fabubaker There are three implementations of distributed tracing (DT) that have emerged over the years.  They all have the same purpose, but how they're implemented is what's different.  Cross application tracing (CAT) was New Relic's very first implementation of distributed tracing and only worked in scenarios where all entities participating in a trace are also instrumented with NR agents and CAT.  Then Distributed Trace (DTnr) came along, which was a much better scheme overall for implementing DT, but is still proprietary format of the header contents to do it's thing and still requires all entities to be instrumented with NR agents.  The latest incarnation is Context Trace, which is an open standard backed by W3C committee.  Both CAT and Distributed Trace have had challenges consistently flowing through network edge devices (firewalls, gateways, etc.) due to how network admins batten down security.  Championing and implementing an open standard was the optimal way to get all players onboard. 

CAT is not needed when either of the latter two solutions are in play, so the intent was to turn it off by default when DT is enabled.  In this case, enabling DT enables both Distributed Trace and Trace Context because they were built for interoperability.  DTnr, like CAT, is deprecated, but it's still serving an active role to give customers time to roll out the W3C enabled agents across all entities in their infrastructure.   If you know you're only using the latest W3C Trace Context version of DT across all the entities you've instrumented, then the optimal configuration is this:

```YAML
  distributed_tracing:
    enabled: true
  exclude_newrelic_header: true
  cross_application_tracer:
    enabled: false
```

**Comment by mwlang** [comment] 2021-04-05 17:20
Closing this issue.  By design, when DT is disabled, CAT is enabled and vice versa.  Since we're moving away from CAT (one of the first and earliest implementations of a form of DT) and embracing an open source version of DT (W3C Trace Context), this issue won't be fixed unless others remote same to raise priority.

**Closed by mwlang** 2021-04-05 17:20 UTC
Labels: bug, community
