### ISSUE TITLE
No Database transactions logged with AWS Aurora 

### ISSUE THREAD

**Issue by hampld** [newrelic/newrelic-ruby-agent#854] opened 2021-11-15 14:59 UTC
## Description
We're running a Rails app on AWS ECS with PGSQL compatible AWS serverless Aurora as the database. No database transactions are recorded by the rubyagent. The pg-database doesn't even show up in the databases overview, however Redis for example does. 

## Expected Behavior
Database transactions get logged by rubyagent.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
```
# Logfile created on 2021-11-12 18:34:51 +0000 by logger.rb/v1.4.2
[2021-11-12 18:34:51 +0000  (8)] INFO : Starting the New Relic agent version 8.0.0 in "production" environment.
[2021-11-12 18:34:51 +0000  (8)] INFO : To prevent agent startup add a NEW_RELIC_AGENT_ENABLED=false environment variable or modify the "production" section of your newrelic.yml.
[2021-11-12 18:34:51 +0000  (8)] INFO : Reading configuration from config/newrelic.yml (/app)
[2021-11-12 18:34:51 +0000  (8)] WARN : Agent is configured to send raw SQL to the service
[2021-11-12 18:34:51 +0000  (8)] INFO : Environment: production
[2021-11-12 18:34:51 +0000  (8)] INFO : No known dispatcher detected.
[2021-11-12 18:34:51 +0000  (8)] INFO : Application: Scout
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing New Relic supported Rack instrumentation using Prepend
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing New Relic supported URLMap instrumentation using Prepend
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing Sidekiq instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing Net:HTTP Wrappers
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing New Relic supported NetHTTP instrumentation using Prepend
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing notifications based Active Record instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing Redis Instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing New Relic supported Redis instrumentation using Prepend
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing ActiveStorage 5 instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing ActiveJob instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing Rails 3+ middleware instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing notifications based Action Controller instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Installing notification based Action View instrumentation
[2021-11-12 18:34:51 +0000  (8)] INFO : Finished instrumentation
[2021-11-12 18:34:51 +0000  (8)] WARN : The method cross_application_tracer is deprecated.
[2021-11-12 18:34:51 +0000  (8)] WARN : [DEPRECATED] Cross application tracing is enabled. Distributed tracing is replacing cross application tracing as the default means of tracing between services. To continue using cross application tracing, enable it with `cross_application_tracer.enabled: true` and `distributed_tracing.enabled: false`
[2021-11-12 18:34:51 +0000  (8)] INFO : Reporting to: https://rpm.newrelic.com/accounts/xxx/applications/yyy
[2021-11-12 18:53:08 +0000  (47)] WARN : Ignoring addition of NewRelic::Agent::Samplers::CpuSampler because it is already registered.
[2021-11-12 18:53:08 +0000  (47)] WARN : Ignoring addition of NewRelic::Agent::Samplers::MemorySampler because it is already registered.
[2021-11-12 18:53:08 +0000  (47)] WARN : Ignoring addition of NewRelic::Agent::Samplers::VMSampler because it is already registered.
[2021-11-12 18:53:10 +0000  (47)] INFO : Reporting to: https://rpm.newrelic.com/accounts/xxx/applications/yyy
[2021-11-12 19:23:09 +0000  (46)] WARN : Ignoring addition of NewRelic::Agent::Samplers::CpuSampler because it is already registered.
[2021-11-12 19:23:09 +0000  (46)] WARN : Ignoring addition of NewRelic::Agent::Samplers::MemorySampler because it is already registered.
[2021-11-12 19:23:09 +0000  (46)] WARN : Ignoring addition of NewRelic::Agent::Samplers::VMSampler because it is already registered.
[2021-11-12 19:23:10 +0000  (46)] INFO : Reporting to: https://rpm.newrelic.com/accounts/xxx/applications/yyy
```
NR Diag did not give errors.

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information
ruby 2.7.2
rubyagent 8.0.0
server: AWS Fargate 1.4.0

## Additional context
https://discuss.newrelic.com/t/ruby-aws-rds-serverless-pgsql-not-showing-up-in-rails-app/166509 no joy.

**Comment by tannalynn** [comment] 2021-11-15 19:17
Hello @hampld,
I talked with our support team this morning and shared this issue and the explorers hub post with them, and they will be reaching out to you to get a support ticket started for this issue. 

Redis is instrumented individually, while postgres is instrumented through active record, which may explain why only redis transactions are present in the UI. I see in the log snippet you provided that active record instrumentation is being installed though, so I'm not sure what might be going wrong with it.


Since it isn't clear what might be causing this missing data, and it may potentially be related to the agent interacting with your specific application/environment/configuration, a support ticket will allow us to privately request additional information and full log files that will help us narrow down our investigation and figure out what might be going on.

I'll be closing this issue here since we will track this issue through support. Please keep an eye out for the ticket from support.

Thank you.

**Closed by tannalynn** 2021-11-15 19:17 UTC
Labels: bug, community

**Comment by hampld** [comment] 2021-11-16 07:27
Hello @tannalynn, 

Thanks for letting me know. I'll wait for support to start working on this. 

Cheers

**Comment by NielsKSchjoedt** [comment] 2021-12-08 09:51
Were there any solution to this?

**Comment by hampld** [comment] 2021-12-09 08:04
no, and support has not reached out so far, at least not in any helpful way.

**Comment by tannalynn** [comment] 2021-12-09 17:09
> no, and support has not reached out so far, at least not in any helpful way.

I'm so sorry about that @hampld, I didn't realize that they hadn't reached out yet! I just checked in with the support team and you should be getting a message from them today about this issue. If you don't see anything from them by tomorrow, please let me know.

**Comment by hampld** [comment] 2021-12-10 07:50
Good morning @tannalynn, sorry to bother you again, but I haven't heard from support yesterday.

**Comment by tannalynn** [comment] 2021-12-10 17:05
@hampld oh, you are absolutely not bothering me! and I'm so sorry you haven't heard back yet! I'll go bug the support people to see what happened with the ticket they created yesterday and let you know what's up with that! 
Also, a sneak peek of the first things we'll be wanting to get from you will be your newrelic.yml and full debug level logs (which we'll get from you privately through the support ticket) for a time period during when the issue is occurring. I figured I'd let you know about the logs now in case you wanted to get the debug logs ready while I try to straighten out whats up with the support ticket. 
Again, so sorry about the delays, and thank you so much for your patience while I try to figure out what is going on with the support ticket.

**Comment by tannalynn** [comment] 2021-12-11 00:30
OK, @hampld. A new ticket has been created today and they just confirmed to me that have now sent an email out to you through the support ticket. You should already have that email right now, but please definitely let me know if you aren't seeing anything. Again, thank you so much for your patience with this.
