### ISSUE TITLE
Big Sur Bug 'require': cannot load such file

### ISSUE THREAD

**Issue by TheSavageDev** [newrelic/newrelic-ruby-agent#528] opened 2020-12-18 21:52 UTC
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
Describe the problem you're encountering.
TIP: Do NOT share sensitive information, whether personal, proprietary, or otherwise! 

When running a server with ruby 2.6.x I consistently get the error:

'require': cannot load such file -- /path/to/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/data_mapper.rb (LoadError)

The file changes but it is always this gem.

## Expected Behavior
Tell us what you expected to happen.
The server to run without error

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

```sh
15:44:56 web.1        | /Users/username/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require': Interrupted system call -- /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/data_mapper.rb (LoadError)
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `block in require'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:257:in `load_dependency'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/activesupport-5.2.4.4/lib/active_support/dependencies.rb:291:in `require'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:19:in `block in load_instrumentation_files'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:17:in `glob'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:17:in `load_instrumentation_files'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:64:in `block in _install_instrumentation'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:64:in `each'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:64:in `_install_instrumentation'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instrumentation.rb:48:in `install_instrumentation'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/new_relic/control/instance_methods.rb:76:in `init_plugin'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/newrelic_rpm-6.14.0/lib/newrelic_rpm.rb:41:in `block in <class:Railtie>'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `instance_exec'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:32:in `run'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:61:in `block in run_initializers'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `call'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `call'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `call'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `each'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:50:in `tsort_each_child'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `call'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `call'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
15:44:56 web.1        |         from /Users/username/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/initializable.rb:60:in `run_initializers'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/application.rb:361:in `initialize!'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `public_send'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/railties-5.2.4.4/lib/rails/railtie.rb:190:in `method_missing'
15:44:56 web.1        |         from /Users/username/dev/path/to/engine/config.ru:7:in `block in <main>'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/bin/rackup:23:in `load'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/bin/rackup:23:in `<main>'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
15:44:56 web.1        |         from /Users/username/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
```

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 
I will try to get a scrubbed repo up soon.

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information
.rvm@1.29.10
ruby 2.6.2 and 2.6.4 (tried both)
Mac OS 11.1
newrelic_rpm-6.14.0

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.
https://stackoverflow.com/questions/65266692/big-sur-ruby-cannot-load-such-file-interrupted-system-call

These did not fix my issue.

**Comment by TheSavageDev** [comment] 2020-12-18 22:34
Also tried with latest version of rbenv

**Comment by mwlang** [comment] 2020-12-18 23:04
Hi, @TheSavageDev  Thank you for submitting this issue.  We have not moved to Ben Sur yet ourselves, but that's coming up soon!  In the meantime, I'll try to help you through.

I get the sense this problem may be related to compiling OpenSSL with Ruby on Ben Sur.  The SO you linked and some of the links I followed from there led mostly to issues with OpenSSL, so let's start there:  

Could you provide the output of `curl -Lks 'https://git.io/rg-ssl' | ruby`
I am expecting something along the lines of this:
```
>> curl -Lks 'https://git.io/rg-ssl' | ruby
Here's your Ruby and OpenSSL environment:

Ruby:           2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
RubyGems:       3.0.3
Bundler:        2.1.4
Compiled with:  OpenSSL 1.1.1h  22 Sep 2020
Loaded version: OpenSSL 1.1.1h  22 Sep 2020
SSL_CERT_FILE:  /Users/mlang/.rbenv/versions/2.6.6/openssl/ssl/cert.pem
SSL_CERT_DIR:   /Users/mlang/.rbenv/versions/2.6.6/openssl/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       success ✅
RubyGems connection to rubygems.org:      success ✅
Ruby net/http connection to rubygems.org: success ✅
```

Are you using the [Data Mapper](https://rubygems.org/gems/datamapper) gem in your project?  If not, is `::DataMapper` defined somewhere in your project?  Lastly, there may be more pertinent details written to the `log/newrelic_agent.log` file that might shed some light on this particular error.  Definitely check that and/or add :debug logging level to your newrelic.yml as [described here](https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration#log_level).

Also, please note that the maintainers will be sporadically available during the holidays.

**Comment by CT014330** [comment] 2020-12-19 16:03
@TheSavageDev thanks for posting this!

@mwlang I am experiencing the same issue.  I did the ssl command and here is the output:
```
Here's your Ruby and OpenSSL environment:

Ruby:           2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin20]
RubyGems:       3.0.9
Bundler:        1.17.3
Compiled with:  OpenSSL 1.1.1i  8 Dec 2020
Loaded version: OpenSSL 1.1.1i  8 Dec 2020
SSL_CERT_FILE:  /usr/local/etc/openssl@1.1/cert.pem
SSL_CERT_DIR:   /usr/local/etc/openssl@1.1/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       success ✅
RubyGems connection to rubygems.org:      success ✅
Ruby net/http connection to rubygems.org: success ✅
```
I do not have the Data Mapper gem or ::DataMapper in the project that I can find.  Attached the newrelic_agent.log from an attempted run that recreated the issue.

Thanks for the help and happy holidays!

[newrelic_agent.log](https://github.com/newrelic/newrelic-ruby-agent/files/5719735/newrelic_agent.log)

**Comment by TheSavageDev** [comment] 2020-12-21 16:33
Thank you @mwlang here is the curl output:

```sh
Here's your Ruby and OpenSSL environment:

Ruby:           2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
RubyGems:       3.0.3
Bundler:        1.17.2
Compiled with:  LibreSSL 2.8.3
Loaded version: LibreSSL 2.8.3
SSL_CERT_FILE:  /private/etc/ssl/cert.pem
SSL_CERT_DIR:   /private/etc/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       success ✅
RubyGems connection to rubygems.org:      success ✅
Ruby net/http connection to rubygems.org: success ✅

Hooray! This Ruby can connect to rubygems.org. You are all set to use Bundler and RubyGems. 👌
```
Looks like #474 might be related. Looking at @CT014330 's newrelic_agent.log it looks like the regex issue. When I look for the code change for that issue (https://github.com/newrelic/newrelic-ruby-agent/pull/476) it looks like it made it to dev but not the 6.14.0 release tag.

**Comment by tannalynn** [comment] 2020-12-22 19:58
@TheSavageDev
I just confirmed that [that change is included in the 6.14.0 release](https://github.com/newrelic/newrelic-ruby-agent/blob/6.14.0/lib/new_relic/agent/samplers/memory_sampler.rb#L32). 
However, it does look like they are using version 6.13.0, which was before those changes were released. This would explain that line in the logs, however, I don't believe lacking that change would cause issues with being unable to load gem files.

@CT014330
can you confirm you are using 6.13.0? Also, are you getting the same error for the same file (Datamapper) is in the error from the original post, or for various files like OP mentioned as well?

This issue is very odd, because the error is that seemingly random files (if i understood you correctly) that are included in the gem, are unable to be loaded by ruby. The gem is definitely including those files when building the gem for release, so I can't see any reason that these files would not exist only in certain situations. We haven't change the way (or the files) we use when building the gem recently, so this seems unrelated to any changes we've made, and it seems to only occur on Big Sur. 
This leads me to believe it is most likely an environment issue, rather than an issue with the agent itself. 
Have you installed any system updates recently? I use a mac as well (although we are still on Catalina), and I have seen similar load errors for files in random gems. In my case, these problems were caused by a system update on my mac. I have had multiple mac updates that messed with my ruby builds actually.  Most recently, This happened for me about a month ago and it required me to totally reinstall things. What worked for me this last time to fix these errors was to:
1. reinstall xcode-tools
2. uninstall all my ruby builds
3. reinstall ruby versions i needed
4. install gems again

Hopefully that helps! Please let us know if you continue having issues after trying that out.

**Comment by CT014330** [comment] 2021-01-03 13:18
@tannalynn I am using 6.13.0 and the error occurs in random files the same as @TheSavageDev.

**Comment by mwlang** [comment] 2021-01-05 18:59
@CT014330 and @TheSavageDev I am back from holiday break and looking at this issue again.  So we've definitively ruled out OpenSSL as potential culprit.   #474 and #476 are for recognizing the OS the agent is actively running on and shouldn't be a factor in this particular issue. 

I do believe the StackOverflow article referenced above is in play here and perhaps even this one as well: https://stackoverflow.com/questions/65084827/big-sur-update-leads-to-multiple-load-error-rails-ruby

The concern here is that the SO author seems to indicate that Ruby needs to be compiled `MAKE_OPTS=-j2` as [described here](https://github.com/rbenv/ruby-build/wiki#cannot-load-such-file----auto_gem).  I don't quite get how _that_ particular complier option solves the runtime error loading files.

**Comment by CT014330** [comment] 2021-01-05 19:40
@mwlang I tried the compiler options suggested in the SO article and it did not solve the problem.  @TheSavageDev did share a workaround with me of locally disabling the new relic agent by updating the env.list file with `NEW_RELIC_AGENT_ENABLED=false` and I no longer see the error, which indicates to me that it is something specific to the new_relic_agent gem.

**Comment by mwlang** [comment] 2021-01-05 20:17
Thanks for sharing that info.  Once we get this next release out the door, I believe the next step is to install Big Sur ourselves as we otherwise have no way to reproduce.

**Comment by akihitoalextsuboi** [comment] 2021-01-08 12:02
@CT014330 @mwlang 
Hi we've solved this issue.
With 

```
OS: Big Sur OS 
CPU: Apple Silicon M1
rbenv by brew
rbenv depends on /usr/local/opt/openssl@1.1/bin/openssl
```

check openssl path with 

```
% which openssl
/opt/homebrew/openssl # or something like this
```

```
# add this to zsh or bash file
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"

# run this
gem uninstall newrelic_rpm
# Recommended to restart your terminal to switch openssl path
```

```
gem install newrelic_rpm
```

successfully installed newrelic_rpm.

**Comment by mwlang** [comment] 2021-01-08 12:10
@akihitoalextsuboi That's interesting!  Any idea why uninstalling and reinstalling the gem is needed here?  there's no natively compiled components to the Ruby agent, so I'm trying to fathom what changes occur with an uninstall followed by an install in this context.

**Comment by CT014330** [comment] 2021-01-20 22:41
I did not have the same success with re-installing the newrelic_rpm gem as @akihitoalextsuboi but I am using rvm, so that could be a factor.  Locally I am able to work around the issue based on a suggestion from @TheSavageDev to just disable the ruby again in the env.list, which does eliminate the issue on my local machine.

**Comment by wingice** [comment] 2021-03-03 07:47
same here after upgrading to big sur 11.2.2

**Comment by tannalynn** [comment] 2021-05-13 23:24
Closing this issue as this appears to be an environment related issue with ruby after upgrading to big sur, and not an issue with the gem itself.

**Closed by tannalynn** 2021-05-13 23:24 UTC
Labels: bug, community
