### ISSUE TITLE
Async 2.6.0 & fiber-annotation

### ISSUE THREAD

**Issue by travisbell** [newrelic/newrelic-ruby-agent#2062] opened 2023-06-08 20:27 UTC
Async 2.6.0 brings in a new dependency with [`fiber-annotation`](https://github.com/ioquatix/fiber-annotation) which I believe is causing some issues with the fiber instrumentation:

```ruby
Exception: ArgumentError
Error: wrong number of arguments (given 1, expected 0)
/usr/local/bundle/gems/fiber-annotation-0.2.0/lib/fiber/annotation.rb:13:in `initialize'
/usr/local/bundle/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/fiber/prepend.rb:14:in `block in initialize'
/usr/local/bundle/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/fiber/instrumentation.rb:11:in `initialize_with_newrelic_tracing'
/usr/local/bundle/gems/newrelic_rpm-9.2.2/lib/new_relic/agent/instrumentation/fiber/prepend.rb:14:in `initialize'
/usr/local/bundle/gems/async-2.6.0/lib/async/task.rb:346:in `new'
/usr/local/bundle/gems/async-2.6.0/lib/async/task.rb:346:in `schedule'
/usr/local/bundle/gems/async-2.6.0/lib/async/task.rb:179:in `run'
/usr/local/bundle/gems/async-2.6.0/lib/async/scheduler.rb:283:in `async'
/usr/local/bundle/gems/async-2.6.0/lib/async/scheduler.rb:247:in `run'
/usr/local/bundle/gems/async-2.6.0/lib/kernel/async.rb:32:in `Async'
```

This is on Ruby 3.2.2 and `newrelic_rpm` 9.2.2.

**Comment by tannalynn** [comment] 2023-06-12 18:45
Hello @travisbell 
Thanks for bringing this to our attention.

We don't have support for the Async gem, which is why this was not noticed by us when it was released. It looks like the issue is because we forward `*args` in our instrumentation, but it seems that isn't compatible with the way initialize is defined in fiber annotation. We'll take a look at what we could do to avoid this issue.

In the mean time though, disabling the fiber instrumentation (using `instrumentation.fiber: disabled` in your newrelic.yml) should prevent this error from happening.

**Comment by tannalynn** [comment] 2023-06-16 16:47
I was able to reproduce this issue easily using Async 2.6.2, so I was able to make updates to the agent that will prevent this issue from happening in the future #2083. We discovered the issue is because the agent was treating Thread and Fiber the same way, but the args passed to the block work differently for thread and fibers. This is now fixed. 
This change will be included in our next release, thank you for bringing this to our attention!

**Closed** 2023-06-16 16:47 UTC
Labels: bug, community

**Comment by ioquatix** [comment] 2023-06-28 21:23
For reference, if you DO want to support the async gem, please don't monkey patch it, and instead write `traces-backend-newrelic` and `metrics-backend-newrelic`.

- https://github.com/socketry/traces
- https://github.com/socketry/metrics

Thanks!
