### ISSUE TITLE
Set transaction name with :uri option substitutes last '/' with '#'

### ISSUE THREAD

**Issue by nonlandi** [newrelic/newrelic-ruby-agent#649] opened 2021-04-21 09:01 UTC
## Description
I am setting a transaction name with the `:uri` option. The transaction name is constructed and set like so
```ruby
tx_name = "#{method} #{uri}"
NewRelic::Agent.set_transaction_name(tx_name, category: :uri)
```

## Expected Behavior
With the given values
```ruby
method="GET"
uri="/feature/v1/users"
```
I am expecting the transaction name to result in
```ruby
GET /feature/v1/users
```
## Bug
Due to some server side processing the resulting transaction name looks like so
```ruby
GET /feature/v1#users
```
If given the option `:uri` I do not expect any altering of the transaction name. The replacement with `#` alters the semantic of the URI, as the `#` would indicate a [URI fragment.
](https://en.wikipedia.org/wiki/URI_fragment)
## Environment
NewRelic agent 6.15.0
JRuby 9.2.17.0

**Comment by tannalynn** [comment] 2021-04-27 23:17
Thanks for bringing this to our attention. We appreciate it.
I was able to replicate this behavior that you described by following your steps, and can confirm that is what the UI is showing. I ran our audit logs while I tested this, and I was able to confirm that the agent itself is sending this data correctly (as `GET /feature/v1/users`) to the new relic servers. Unfortunately, any transformations happening on the server side are not something the agent is able to control.
I would recommend that you file exactly what was written to Explorer’s hub (https://discuss.newrelic.com/).
If you are an enterprise customer,  please file a ticket with Technical support (https://support.newrelic.com/).
Since this issue is not a bug within the agent code, I’ll be closing this issue.

**Closed by tannalynn** 2021-04-27 23:17 UTC
Labels: community
