### ISSUE TITLE
Remove CAT deprecation warning if not enabled

### ISSUE THREAD

**Issue by alpha-san** [newrelic/newrelic-ruby-agent#827] opened 2021-11-01 19:39 UTC
### Is your feature request related to a problem? Please describe.
I keep getting deprecation warning message for cross application tracing despite enabling distributed tracing and explicitly setting `cross_application_tracer.enabled` to false. Would it be possible to remove the deprecation warning if `CrossAppTracing.cross_app_enabled?` is false?

### Feature Description
Remove CAT deprecation warning if `cross_application_tracer.enabled` is set to false in config

### Priority
Please help us better understand this feature request by choosing a priority from the following options: 
**Nice to Have**

**Comment by tannalynn** [comment] 2021-11-01 21:58
hello @alpha-san 
Thank you for bringing this to our attention. What you are describing was the intended behavior of the warning, however it seems we have placed this warning in a location that is always called when the agent starts. I have added a check for that in #828, so this will be fixed in a future release of the agent.

**Closed** 2021-11-01 23:01 UTC
Labels: bug
