### ISSUE TITLE
Adding method traces can break ruby module constant resolution

### ISSUE THREAD

**Issue by Goltergaul** [newrelic/newrelic-ruby-agent#1221] opened 2022-06-24 09:30 UTC
## Description
```
module Foobar
  include NewRelic::Agent::MethodTracer
  TESTCONSTANT = "bar"

  def foo
    nil
  end
  #add_method_tracer :foo
end

class Bar
  include NewRelic::Agent::MethodTracer
  include Foobar


  def test
    nil
  end
  add_method_tracer :test
end

[1] pry(main)> Foobar::TESTCONSTANT
=> "bar"
[2] pry(main)> Bar::TESTCONSTANT
=> "bar"
```

But when the method tracer in Foobar is added the suddendly Bar::TESTCONSTANT is undefined:
```
module Foobar
  include NewRelic::Agent::MethodTracer
  TESTCONSTANT = "bar"

  def foo
    nil
  end
  add_method_tracer :foo
end

class Bar
  include NewRelic::Agent::MethodTracer
  include Foobar


  def test
    nil
  end
  add_method_tracer :test
end

[1] pry(main)> Foobar::TESTCONSTANT
=> "bar"
[2] pry(main)> Bar::TESTCONSTANT
NameError: uninitialized constant Bar::TESTCONSTANT
from org/jruby/RubyModule.java:3948:in `const_missing'
```

## Expected Behavior
Bar::TESTCONSTANT should still resolve correctly

## Your Environment

- newrelic_rpm 8.8.0
- jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.15+10-Ubuntu-0ubuntu0.20.04.1 on 11.0.15+10-Ubuntu-0ubuntu0.20.04.1 +jit [x86_64-linux]

It  WORKS with `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]` but not with above mentioned jruby version
It might be a jruby issue? Not sure though

**Comment by tannalynn** [comment] 2022-06-24 23:27
@Goltergaul Thank you for reporting this issue you are experiencing. I appreciate the reproduction snippet, with that I was able to reproduce the issue. I was able to narrow in on our use of Module#prepend as the cause of the issue. In 8.0.0, we refactored add_method_tracer to use Module#prepend instead of method chaining, and saw that versions of the agent prior to this does not experience the same issue. 
I checked all of our supported ruby versions, and can confirm that this issue is only present when using jruby. Using your example, I modified the code to do the most basic version of what the agent is doing when tracing methods (using prepend when add_method_tracer is called), and I was able to reproduce the issue without the ruby agent.  Using the code below, I was able to reproduce the exact same `NameError: uninitialized constant Bar::TESTCONSTANT` when using jruby. 

```
module PrependTest
  def foo
    nil
  end
end

module Foobar
  prepend PrependTest
  TESTCONSTANT = "bar"
  def foo
    nil
  end
end

class Bar
  include Foobar
  def test
    nil
  end
end

Foobar::TESTCONSTANT
Bar::TESTCONSTANT
```

This looks like it's a bug in the jruby language unfortunately. I opened an issue in the jruby repo to report this bug to them https://github.com/jruby/jruby/issues/7256

In the meantime, while not ideal because it would be missing out on newer agent features, older versions of the agent < 8.0.0 should be able to use add_method_tracer since it is using the older style of alias_method instead of Module#prepend. 

I'm going to go ahead and close this issue because I don't believe there is much we'll be able to do about this bug on the ruby agent team, unfortunately. I'm sorry we don't have a solution for this issue, but please let me know if there is anything I can do to help.

**Closed** 2022-06-24 23:27 UTC
Labels: bug, community

**Comment by nonlandi** [comment] 2022-06-27 05:42
@tannalynn Thank you for your swift help diagnosing the issue. Appreciate it!

**Comment by Goltergaul** [comment] 2022-06-27 06:15
Thanks @tannalynn we'll track the jruby issue
